SET SCAMP_ENABLE_BINARY_DISTRIBUTION=ON
SET SCAMP_USE_EXTERNAL_EIGEN=ON
SET PYSCAMP_USE_EXTERNAL_PYBIND11=ON
REM Pin version so setuptools_scm does not produce a local-version string
SET SETUPTOOLS_SCM_PRETEND_VERSION=4.0.2dev0
SET VERBOSE=ON
"%PYTHON%" setup.py install
