{% set name = "pyscamp" %}
{% set version = "4.0.0" %}


package:
  name: {{ name|lower }}-cpu
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyscamp-{{ version }}.tar.gz
  sha256: 7cbcd1400c18b908aea8be0cb9fcb6305500ff29737f67db456ff607308af8e4

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]

  host:
    - python
    - setuptools-scm
    - pybind11 2.9.2
    - eigen 3.4.0

  run:
    - python

test:
  source_files:
    - test
  imports:
    - pyscamp
  commands:
    - pip check
    - cd test
    - python test_pyscamp.py
  requires:
    - pip
    - numpy

about:
  home: https://github.com/zpzim/SCAMP
  summary: SCAlable Matrix Profile
  license: MIT
  license_file:
    - LICENSE
    - third_party/cpu_features/LICENSE

extra:
  recipe-maintainers:
    - zpzim
