{% set name = "pyscamp" %}
{% set version = "4.0.2.dev2" %}

package:
  name: {{ name|lower }}-cpu
  version: {{ version }}

source:
  # Testing SCAMP PR #137 against test.pypi.org pre-release sdist.
  # Switch back to https://pypi.io/... once v4.0.2 is released.
  url: https://test-files.pythonhosted.org/packages/60/54/88cd2781aaf9d0903fb43470e4f1cb0f1e3b94251c091a1b45bb8f98c585/pyscamp-{{ version }}.tar.gz
  sha256: afe41406271786b40dd34369e812fcc6076c4f92d5f11e7894eb8028965ed786

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [not win]

  host:
    - python
    - setuptools >=70
    - setuptools-scm
    - pybind11 >=2.13.6
    - eigen 3.4.0

  run:
    - python

test:
  source_files:
    - test
  imports:
    - pyscamp
  commands:
    - pip check
    - cd test
    - python test_pyscamp.py
  requires:
    - pip
    - numpy

about:
  home: https://github.com/zpzim/SCAMP
  summary: SCAlable Matrix Profile
  license: MIT
  license_file:
    - LICENSE
    - third_party/cpu_features/LICENSE

extra:
  recipe-maintainers:
    - zpzim
