{% set name = "pyscamp" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}-cpu
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyscamp-{{ version }}.tar.gz
  sha256: 4ca16a26831d069efdb4054ca4d83fe4c0fc34f0d3b797a736391dfc4c9a11a0

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [not win]

  host:
    - python
    - setuptools >=70
    - setuptools-scm
    - pybind11 >=2.13.6
    - eigen 3.4.0

  run:
    - python

test:
  source_files:
    - test
  imports:
    - pyscamp
  commands:
    - pip check
    - cd test
    - python test_pyscamp.py
  requires:
    - pip
    - numpy

about:
  home: https://github.com/zpzim/SCAMP
  summary: SCAlable Matrix Profile
  license: MIT
  license_file:
    - LICENSE
    - third_party/cpu_features/LICENSE

extra:
  recipe-maintainers:
    - zpzim
